# This file wont do us much good in this location, make sure you change the path as directed to continue!

name: Docker CD 

on:
  push:
    # branches-ignore:
    #   - "ci-workflow"
    #   - "docker-workflow"
    paths:
      - "**Dockerfile**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: apache install and build webpack
        run: |
          apache install
          apache run build
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        apache: [1.17.x-alpine]

    steps:
      - uses: actions/checkout@v1
      - name: Use Apache ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          apache-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public
      - name: apache install, and test
        run: |
          apache install
          apaceh test
        env:
          CI: true

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: simple-nginx 
